def ImportJSON(data: bytes) -> None: ...
def ImportCSVConsultants(data: bytes) -> None: ...
def ImportCSVCustomers(data: bytes) -> None: ...
def ImportCSVBooking(data: bytes) -> None: ...
def AiConsultantsSummary() -> bytes: ...
